import React, { useEffect, useMemo, useState } from "react";

type ArtifactKind = "json" | "text";

type ArtifactDef = {
  id: string;
  title: string;
  path: string;
  kind: ArtifactKind;
  description: string;
};

type LoadState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "missing"; message: string }
  | { status: "error"; message: string }
  | { status: "loaded"; rawText: string; prettyText?: string; json?: unknown };

type ReplayInfo = {
  selected_request_hash?: string;
  malformed_ndjson_lines_ignored?: number;
  selected_index?: number | null;
};

async function fetchTextStrict(path: string): Promise<{ ok: boolean; status: number; text: string }> {
  const res = await fetch(path, { cache: "no-store" });
  const text = await res.text();
  return { ok: res.ok, status: res.status, text };
}

function tryParseJson(raw: string): { ok: true; json: unknown; pretty: string } | { ok: false; error: string } {
  try {
    const parsed = JSON.parse(raw);
    return { ok: true, json: parsed, pretty: JSON.stringify(parsed, null, 2) };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}

function extractReplayInfo(jsonValue: unknown): ReplayInfo | null {
  if (!jsonValue || typeof jsonValue !== "object") return null;

  const obj = jsonValue as Record<string, unknown>;
  const replay = obj["_replay"];

  if (!replay || typeof replay !== "object") return null;

  const r = replay as Record<string, unknown>;
  const info: ReplayInfo = {};

  if (typeof r["selected_request_hash"] === "string") info.selected_request_hash = r["selected_request_hash"];
  if (typeof r["malformed_ndjson_lines_ignored"] === "number")
    info.malformed_ndjson_lines_ignored = r["malformed_ndjson_lines_ignored"];
  if (typeof r["selected_index"] === "number" || r["selected_index"] === null) info.selected_index = r["selected_index"] as
    | number
    | null;

  const hasAny =
    typeof info.selected_request_hash === "string" ||
    typeof info.malformed_ndjson_lines_ignored === "number" ||
    typeof info.selected_index === "number" ||
    info.selected_index === null;

  return hasAny ? info : null;
}

export function ArtifactsPanel() {
  const artifacts: ArtifactDef[] = useMemo(
    () => [
      {
        id: "last_prd",
        title: "last_prd.json",
        path: "/last_prd.json",
        kind: "json",
        description: "Product Requirement Document generated by PM agent (Phase 5 multi-agent).",
      },
      {
        id: "last_execution_request",
        title: "last_execution_request.json",
        path: "/last_execution_request.json",
        kind: "json",
        description: "Most recent request emitted by the orchestrator (runtime artifact).",
      },
      {
        id: "last_execution_result",
        title: "last_execution_result.json",
        path: "/last_execution_result.json",
        kind: "json",
        description: "Most recent execution result produced by the consumer (runtime artifact).",
      },
      {
        id: "last_evaluation_result",
        title: "last_evaluation_result.json",
        path: "/last_evaluation_result.json",
        kind: "json",
        description: "Most recent evaluation result produced by the evaluator (runtime artifact).",
      },
    ],
    []
  );

  const [selectedId, setSelectedId] = useState<string>(artifacts[0]?.id ?? "");
  const selected = useMemo(
    () => artifacts.find((a) => a.id === selectedId) ?? artifacts[0],
    [artifacts, selectedId]
  );

  const [state, setState] = useState<LoadState>({ status: "idle" });

  const replayInfo = useMemo(() => {
    if (!selected) return null;
    if (selected.id !== "last_execution_result") return null;
    if (state.status !== "loaded") return null;
    return extractReplayInfo(state.json);
  }, [selected, state]);

  useEffect(() => {
    let cancelled = false;
    if (!selected) return;

    (async () => {
      setState({ status: "loading" });
      const res = await fetchTextStrict(selected.path);

      if (cancelled) return;

      if (!res.ok) {
        if (res.status === 404) {
          setState({ status: "missing", message: `Missing (${res.status}). File not found at ${selected.path}` });
          return;
        }

        setState({ status: "error", message: `Failed to fetch ${selected.path}: ${res.status}` });
        return;
      }

      const rawText = res.text;

      if (selected.kind === "json") {
        const parsed = tryParseJson(rawText);
        if (!parsed.ok) {
          setState({
            status: "error",
            message: `JSON parse error in ${selected.title}: ${parsed.error}`,
          });
          return;
        }

        setState({ status: "loaded", rawText, prettyText: parsed.pretty, json: parsed.json });
        return;
      }

      setState({ status: "loaded", rawText });
    })().catch((e) => {
      if (cancelled) return;
      setState({ status: "error", message: e instanceof Error ? e.message : String(e) });
    });

    return () => {
      cancelled = true;
    };
  }, [selected]);

  return (
    <section className="panel">
      <div className="panelHeader">
        <h2>Artifacts</h2>
        <p className="muted">
          Read-only runtime artifacts loaded directly from <span className="mono">/public</span>. Missing files and parse
          errors are treated as visible UI state.
        </p>
      </div>

      <div className="panelBody artifactsLayout">
        <div className="card artifactsList">
          <div className="cardTitle">Files</div>
          <div className="artifactsButtons">
            {artifacts.map((a) => (
              <button
                key={a.id}
                type="button"
                className={`artifactBtn ${a.id === selected?.id ? "active" : ""}`}
                onClick={() => setSelectedId(a.id)}
              >
                <div className="artifactBtnTitle mono">{a.title}</div>
                <div className="small">{a.description}</div>
              </button>
            ))}
          </div>
        </div>

        <div className="card artifactsViewer">
          <div className="headerRow">
            <div>
              <div className="cardTitle">Selected</div>
              <div className="mono" style={{ fontSize: 13 }}>
                {selected?.path}
              </div>
            </div>

            <div className={`statusPill ${state.status === "loaded" ? "done" : ""}`} title={state.status}>
              {state.status}
            </div>
          </div>

          {state.status === "loading" ? (
            <div className="muted small" style={{ marginTop: 10 }}>
              Loading...
            </div>
          ) : state.status === "missing" ? (
            <div className="muted small" style={{ marginTop: 10 }}>
              {state.message}
            </div>
          ) : state.status === "error" ? (
            <div className="muted small" style={{ marginTop: 10 }}>
              {state.message}
            </div>
          ) : state.status === "loaded" ? (
            <>
              {replayInfo ? (
                <div className="card" style={{ marginTop: 10, padding: 12 }}>
                  <div className="cardTitle">Replay</div>
                  <div className="small muted" style={{ marginTop: 6 }}>
                    This execution result was produced by <span className="mono">scripts/replay_execution_request.py</span>.
                  </div>

                  <div className="small" style={{ marginTop: 10 }}>
                    <div>
                      <span className="muted">selected_request_hash:</span>{" "}
                      <span className="mono">{replayInfo.selected_request_hash ?? "(missing)"}</span>
                    </div>

                    <div style={{ marginTop: 6 }}>
                      <span className="muted">selected_index:</span>{" "}
                      <span className="mono">
                        {replayInfo.selected_index === null || typeof replayInfo.selected_index === "number"
                          ? String(replayInfo.selected_index)
                          : "(missing)"}
                      </span>
                    </div>

                    <div style={{ marginTop: 6 }}>
                      <span className="muted">malformed_ndjson_lines_ignored:</span>{" "}
                      <span className="mono">
                        {typeof replayInfo.malformed_ndjson_lines_ignored === "number"
                          ? String(replayInfo.malformed_ndjson_lines_ignored)
                          : "(missing)"}
                      </span>
                    </div>
                  </div>
                </div>
              ) : null}

              <pre className="codeBlock" style={{ marginTop: 10 }}>
                {state.prettyText ?? state.rawText ?? "(empty)"}
              </pre>
            </>
          ) : (
            <div className="muted small" style={{ marginTop: 10 }}>
              Select an artifact.
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
