import React from "react";
import { Plan, PlanMilestone, PlanTask, safeArray, isDone } from "../types/plan";

type Props = {
  plan: Plan | null;
  selectedMilestoneIndex: number;
  selectedTaskIndex: number;
  onSelectMilestone: (idx: number) => void;
  onSelectTask: (taskIdx: number) => void;
  filterText: string;
  onChangeFilterText: (v: string) => void;
};

function getMilestoneTitle(m: PlanMilestone, idx: number): string {
  const anyM = m as any;
  return m.title ?? anyM.name ?? `Milestone ${idx + 1}`;
}

function getTaskTitle(t: PlanTask, idx: number): string {
  const anyT = t as any;
  return t.title ?? anyT.name ?? t.id ?? `Task ${idx + 1}`;
}

function countDoneTasks(m: PlanMilestone): { done: number; total: number } {
  const anyM = m as any;
  const tasks = safeArray<PlanTask>(m.tasks ?? anyM.tasks);
  const total = tasks.length;
  const done = tasks.filter(isDone).length;
  return { done, total };
}

export function PlanSidebar(props: Props) {
  const {
    plan,
    selectedMilestoneIndex,
    selectedTaskIndex,
    onSelectMilestone,
    onSelectTask,
    filterText,
    onChangeFilterText,
  } = props;

  const milestones = safeArray<PlanMilestone>(plan?.milestones);

  return (
    <aside className="sidebar">
      <div className="sidebarHeader">
        <div className="sidebarTitle">
          <div className="badge">PLAN</div>
          <h1>{plan?.title ?? "Project Plan"}</h1>
        </div>
        <p className="muted">{plan?.description ?? "Milestones and tasks generated by your Planner."}</p>

        <label className="searchLabel">
          <span className="muted">Search tasks</span>
          <input
            className="searchInput"
            value={filterText}
            onChange={(e) => onChangeFilterText(e.target.value)}
            placeholder="type to filter…"
          />
        </label>
      </div>

      <div className="sidebarBody">
        {milestones.length === 0 ? (
          <div className="emptyState">
            <p>
              <strong>No milestones found.</strong>
            </p>
            <p className="muted">
              Check <code>public/last_plan.json</code> export.
            </p>
          </div>
        ) : (
          milestones.map((m, mi) => {
            const { done, total } = countDoneTasks(m);
            const isSelected = mi === selectedMilestoneIndex;

            return (
              <div
                key={(m as any).id ?? `${mi}`}
                className={`milestoneRow ${isSelected ? "selected" : ""}`}
                role="button"
                tabIndex={0}
                onClick={() => {
                  onSelectMilestone(mi);
                  onSelectTask(0);
                }}
                onKeyDown={(e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    onSelectMilestone(mi);
                    onSelectTask(0);
                  }
                }}
              >
                <div className="milestoneTop">
                  <div className="milestoneName">{getMilestoneTitle(m, mi)}</div>
                  <div className="milestoneMeta">
                    {done}/{total}
                  </div>
                </div>

                <div className="progressBar" aria-hidden="true">
                  <div
                    className="progressFill"
                    style={{ width: total === 0 ? "0%" : `${Math.round((done / total) * 100)}%` }}
                  />
                </div>

                {isSelected ? (
                  <MilestoneTaskList
                    milestone={m}
                    selectedTaskIndex={selectedTaskIndex}
                    onSelectTask={onSelectTask}
                    filterText={filterText}
                  />
                ) : null}
              </div>
            );
          })
        )}
      </div>

      <div className="sidebarFooter">
        <div className="muted small">
          This UI is a deterministic renderer of <code>public/last_plan.json</code>.
        </div>
      </div>
    </aside>
  );
}

function MilestoneTaskList(props: {
  milestone: PlanMilestone;
  selectedTaskIndex: number;
  onSelectTask: (idx: number) => void;
  filterText: string;
}) {
  const anyM = props.milestone as any;
  const tasks = safeArray<PlanTask>(props.milestone.tasks ?? anyM.tasks);
  const filter = props.filterText.trim().toLowerCase();

  const visible = tasks
    .map((t, idx) => ({ t, idx }))
    .filter(({ t }) => {
      if (!filter) return true;
      const anyT = t as any;
      const title = String(t.title ?? anyT.name ?? t.id ?? "").toLowerCase();
      const desc = String(t.description ?? anyT.summary ?? "").toLowerCase();
      return title.includes(filter) || desc.includes(filter);
    });

  return (
    <div className="taskList" onClick={(e) => e.stopPropagation()}>
      {visible.length === 0 ? (
        <div className="muted small">No matching tasks.</div>
      ) : (
        visible.map(({ t, idx }) => {
          const selected = idx === props.selectedTaskIndex;
          const done = isDone(t);

          return (
            <button
              key={(t as any).id ?? `${idx}`}
              className={`taskRow ${selected ? "selected" : ""}`}
              onClick={() => props.onSelectTask(idx)}
              type="button"
            >
              <span className={`dot ${done ? "done" : ""}`} aria-hidden="true" />
              <span className="taskRowTitle">{getTaskTitle(t, idx)}</span>
            </button>
          );
        })
      )}
    </div>
  );
}
