from __future__ import annotations

from dataclasses import dataclass
from typing import Dict


@dataclass(frozen=True)
class OfflineScaffold:
    """
    A deterministic Vite + React + TypeScript scaffold represented as
    a mapping of relative file paths -> file contents.
    """
    files: Dict[str, str]


def build_vite_react_ts_scaffold(app_dir: str = "apps/offline-vite-react") -> OfflineScaffold:
    """
    Returns a deterministic set of files for a Vite+React+TS project.

    IMPORTANT:
    - This function is OFFLINE: it does not call any LLM or external tooling.
    - It only prepares the file contents. Your existing safe-writer should apply them.
    - `app_dir` is a relative directory under repo root.
    """
    base = app_dir.strip("/")

    files: Dict[str, str] = {
        f"{base}/README.md": (
            "# Offline Vite + React (TypeScript)\n\n"
            "This scaffold is generated by the AI Dev Team project's **OFFLINE Engineer** (no model calls).\n\n"
            "## Run\n"
            "```bash\n"
            "npm install\n"
            "npm run dev\n"
            "```\n\n"
            "## Why this exists\n"
            "- Demonstrates deterministic orchestration + safe file writes\n"
            "- Provides a real front-end scaffold you can extend into the Lovable-style experience\n"
        ),
        f"{base}/.gitignore": (
            "node_modules\n"
            "dist\n"
            ".vite\n"
            ".DS_Store\n"
            ".env\n"
            ".env.local\n"
        ),
        f"{base}/package.json": (
            "{\n"
            '  "name": "offline-vite-react",\n'
            '  "private": true,\n'
            '  "version": "0.0.0",\n'
            '  "type": "module",\n'
            '  "scripts": {\n'
            '    "dev": "vite",\n'
            '    "build": "tsc -b && vite build",\n'
            '    "preview": "vite preview"\n'
            "  },\n"
            '  "dependencies": {\n'
            '    "react": "^18.3.1",\n'
            '    "react-dom": "^18.3.1"\n'
            "  },\n"
            '  "devDependencies": {\n'
            '    "@types/react": "^18.3.3",\n'
            '    "@types/react-dom": "^18.3.0",\n'
            '    "@vitejs/plugin-react": "^4.3.1",\n'
            '    "typescript": "^5.5.4",\n'
            '    "vite": "^5.4.1"\n'
            "  }\n"
            "}\n"
        ),
        f"{base}/vite.config.ts": (
            'import { defineConfig } from "vite";\n'
            'import react from "@vitejs/plugin-react";\n\n'
            "export default defineConfig({\n"
            "  plugins: [react()],\n"
            "});\n"
        ),
        f"{base}/tsconfig.json": (
            "{\n"
            '  "compilerOptions": {\n'
            '    "target": "ES2022",\n'
            '    "useDefineForClassFields": true,\n'
            '    "lib": ["ES2022", "DOM", "DOM.Iterable"],\n'
            '    "module": "ESNext",\n'
            '    "skipLibCheck": true,\n\n'
            '    "moduleResolution": "Bundler",\n'
            '    "resolveJsonModule": true,\n'
            '    "isolatedModules": true,\n'
            '    "noEmit": true,\n'
            '    "jsx": "react-jsx",\n\n'
            '    "strict": true,\n'
            '    "types": ["vite/client"]\n'
            "  },\n"
            '  "include": ["src"]\n'
            "}\n"
        ),
        f"{base}/tsconfig.node.json": (
            "{\n"
            '  "compilerOptions": {\n'
            '    "composite": true,\n'
            '    "skipLibCheck": true,\n'
            '    "module": "ESNext",\n'
            '    "moduleResolution": "Bundler",\n'
            '    "allowSyntheticDefaultImports": true\n'
            "  },\n"
            '  "include": ["vite.config.ts"]\n'
            "}\n"
        ),
        f"{base}/index.html": (
            "<!doctype html>\n"
            "<html lang=\"en\">\n"
            "  <head>\n"
            "    <meta charset=\"UTF-8\" />\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
            "    <title>Offline Vite + React</title>\n"
            "  </head>\n"
            "  <body>\n"
            "    <div id=\"root\"></div>\n"
            "    <script type=\"module\" src=\"/src/main.tsx\"></script>\n"
            "  </body>\n"
            "</html>\n"
        ),
        f"{base}/src/main.tsx": (
            'import React from "react";\n'
            'import ReactDOM from "react-dom/client";\n'
            'import App from "./App";\n'
            'import "./index.css";\n\n'
            'ReactDOM.createRoot(document.getElementById("root")!).render(\n'
            "  <React.StrictMode>\n"
            "    <App />\n"
            "  </React.StrictMode>\n"
            ");\n"
        ),
        f"{base}/src/App.tsx": (
            "export default function App() {\n"
            "  return (\n"
            '    <main className="page">\n'
            "      <h1>Offline Engineer Scaffold</h1>\n"
            "      <p>\n"
            "        This project was generated deterministically with <code>OFFLINE_MODE</code>.\n"
            "      </p>\n\n"
            '      <section className="card">\n'
            "        <h2>Next</h2>\n"
            "        <ol>\n"
            "          <li>npm install</li>\n"
            "          <li>npm run dev</li>\n"
            "        </ol>\n"
            "      </section>\n"
            "    </main>\n"
            "  );\n"
            "}\n"
        ),
        f"{base}/src/index.css": (
            ":root {\n"
            "  font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;\n"
            "  line-height: 1.5;\n"
            "  font-weight: 400;\n"
            "}\n\n"
            "body {\n"
            "  margin: 0;\n"
            "}\n\n"
            ".page {\n"
            "  padding: 24px;\n"
            "  max-width: 880px;\n"
            "  margin: 0 auto;\n"
            "}\n\n"
            ".card {\n"
            "  margin-top: 16px;\n"
            "  padding: 16px;\n"
            "  border: 1px solid #e5e7eb;\n"
            "  border-radius: 12px;\n"
            "}\n"
        ),
        f"{base}/src/vite-env.d.ts": '/// <reference types="vite/client" />\n',
    }

    return OfflineScaffold(files=files)
