from __future__ import annotations

from dataclasses import dataclass
from typing import Dict


@dataclass(frozen=True)
class OfflineScaffold:
    """
    A deterministic Vite + React + TypeScript scaffold represented as
    a mapping of relative file paths -> file contents.
    """
    files: Dict[str, str]


def build_vite_react_ts_scaffold(app_dir: str = "apps/offline-vite-react") -> OfflineScaffold:
    """
    Returns a deterministic set of files for a Vite+React+TS project.

    IMPORTANT:
    - This function is OFFLINE: it does not call any LLM or external tooling.
    - It only prepares the file contents. Your existing safe-writer should apply them.
    - `app_dir` is a relative directory under repo root.
    """
    base = app_dir.strip("/")

    def target(path: str) -> str:
        return f"{base}/{path}" if base else path

    files: Dict[str, str] = {
        target("README.md"): (
            "# Offline Vite + React (TypeScript)\n\n"
            "This scaffold is generated by Archon without model calls.\n\n"
            "## Run\n"
            "```bash\n"
            "npm install\n"
            "npm run dev\n"
            "```\n\n"
            "## Why this exists\n"
            "- Demonstrates deterministic orchestration + safe file writes\n"
            "- Provides a real front-end scaffold you can extend into a premium experience\n"
        ),
        target(".gitignore"): (
            "node_modules\n"
            "dist\n"
            ".vite\n"
            ".DS_Store\n"
            ".env\n"
            ".env.local\n"
        ),
        target("package.json"): (
            "{\n"
            '  "name": "offline-vite-react",\n'
            '  "private": true,\n'
            '  "version": "0.0.0",\n'
            '  "type": "module",\n'
            '  "scripts": {\n'
            '    "dev": "vite",\n'
            '    "build": "tsc -b && vite build",\n'
            '    "preview": "vite preview"\n'
            "  },\n"
            '  "dependencies": {\n'
            '    "react": "^18.3.1",\n'
            '    "react-dom": "^18.3.1"\n'
            "  },\n"
            '  "devDependencies": {\n'
            '    "@types/react": "^18.3.3",\n'
            '    "@types/react-dom": "^18.3.0",\n'
            '    "@vitejs/plugin-react": "^4.3.1",\n'
            '    "typescript": "^5.5.4",\n'
            '    "vite": "^5.4.1"\n'
            "  }\n"
            "}\n"
        ),
        target("vite.config.ts"): (
            'import { defineConfig } from "vite";\n'
            'import react from "@vitejs/plugin-react";\n\n'
            "export default defineConfig({\n"
            "  plugins: [react()],\n"
            "});\n"
        ),
        target("tsconfig.json"): (
            "{\n"
            '  "compilerOptions": {\n'
            '    "target": "ES2022",\n'
            '    "useDefineForClassFields": true,\n'
            '    "lib": ["ES2022", "DOM", "DOM.Iterable"],\n'
            '    "module": "ESNext",\n'
            '    "skipLibCheck": true,\n\n'
            '    "moduleResolution": "Bundler",\n'
            '    "resolveJsonModule": true,\n'
            '    "isolatedModules": true,\n'
            '    "noEmit": true,\n'
            '    "jsx": "react-jsx",\n\n'
            '    "strict": true,\n'
            '    "types": ["vite/client"]\n'
            "  },\n"
            '  "include": ["src"]\n'
            "}\n"
        ),
        target("tsconfig.node.json"): (
            "{\n"
            '  "compilerOptions": {\n'
            '    "composite": true,\n'
            '    "skipLibCheck": true,\n'
            '    "module": "ESNext",\n'
            '    "moduleResolution": "Bundler",\n'
            '    "allowSyntheticDefaultImports": true\n'
            "  },\n"
            '  "include": ["vite.config.ts"]\n'
            "}\n"
        ),
        target("index.html"): (
            "<!doctype html>\n"
            "<html lang=\"en\">\n"
            "  <head>\n"
            "    <meta charset=\"UTF-8\" />\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
            "    <title>Archon Offline Preview</title>\n"
            "  </head>\n"
            "  <body>\n"
            "    <div id=\"root\"></div>\n"
            "    <script type=\"module\" src=\"/src/main.tsx\"></script>\n"
            "  </body>\n"
            "</html>\n"
        ),
        target("src/main.tsx"): (
            'import React from "react";\n'
            'import ReactDOM from "react-dom/client";\n'
            'import App from "./App";\n'
            'import "./index.css";\n\n'
            'ReactDOM.createRoot(document.getElementById("root")!).render(\n'
            "  <React.StrictMode>\n"
            "    <App />\n"
            "  </React.StrictMode>\n"
            ");\n"
        ),
        target("src/App.tsx"): (
            "const stages = [\n"
            "  { label: '01', title: 'Product brief', detail: 'Structured locally from the project request' },\n"
            "  { label: '02', title: 'Build plan', detail: 'Validated against the Archon artifact schema' },\n"
            "  { label: '03', title: 'React workspace', detail: 'Compiled into this live preview' },\n"
            "];\n\n"
            "export default function App() {\n"
            "  return (\n"
            '    <main className="offline-shell">\n'
            '      <header className="topbar">\n'
            '        <div className="brand"><span className="brand-mark">A</span><span>ARCHON</span></div>\n'
            '        <span className="status"><i /> Provider-free run</span>\n'
            "      </header>\n\n"
            '      <section className="hero">\n'
            '        <p className="eyebrow">LOCAL PIPELINE READY</p>\n'
            "        <h1>A complete application path, without API credentials.</h1>\n"
            '        <p className="lede">\n'
            "          Archon created this deterministic workspace so every fresh clone can verify the pipeline\n"
            "          before connecting a model provider.\n"
            "        </p>\n"
            '        <div className="stack"><span>React</span><span>TypeScript</span><span>Vite</span></div>\n'
            "      </section>\n\n"
            '      <section className="pipeline" aria-label="Completed pipeline stages">\n'
            "        {stages.map((stage) => (\n"
            '          <article className="stage" key={stage.label}>\n'
            '            <div className="stage-label">{stage.label}</div>\n'
            '            <div><h2>{stage.title}</h2><p>{stage.detail}</p></div>\n'
            '            <span className="check">Ready</span>\n'
            "          </article>\n"
            "        ))}\n"
            "      </section>\n\n"
            '      <section className="next-step">\n'
            "        <div>\n"
            '          <p className="eyebrow">NEXT STEP</p>\n'
            "          <h2>Connect a provider when you want generated output.</h2>\n"
            "        </div>\n"
            '        <code>OFFLINE_MODE=false</code>\n'
            "      </section>\n"
            "    </main>\n"
            "  );\n"
            "}\n"
        ),
        target("src/index.css"): (
            ":root {\n"
            "  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif;\n"
            "  color: #eef2ff;\n"
            "  background: #080b12;\n"
            "  font-synthesis: none;\n"
            "}\n\n"
            "* { box-sizing: border-box; }\n\n"
            "body {\n"
            "  margin: 0;\n"
            "  min-width: 320px;\n"
            "  min-height: 100vh;\n"
            "  background:\n"
            "    radial-gradient(circle at 80% 0%, rgba(98, 102, 241, 0.18), transparent 34rem),\n"
            "    #080b12;\n"
            "}\n\n"
            ".offline-shell {\n"
            "  width: min(1120px, calc(100% - 40px));\n"
            "  margin: 0 auto;\n"
            "  padding: 28px 0 72px;\n"
            "}\n\n"
            ".topbar { display: flex; align-items: center; justify-content: space-between; }\n"
            ".brand { display: flex; align-items: center; gap: 10px; font-weight: 800; letter-spacing: 0.12em; }\n"
            ".brand-mark { display: grid; place-items: center; width: 34px; height: 34px; border-radius: 10px; background: #818cf8; color: #090b12; }\n"
            ".status { display: flex; align-items: center; gap: 8px; color: #aeb6ca; font-size: 13px; }\n"
            ".status i { width: 8px; height: 8px; border-radius: 50%; background: #4ade80; box-shadow: 0 0 18px #4ade80; }\n\n"
            ".hero { padding: 116px 0 72px; max-width: 880px; }\n"
            ".eyebrow { margin: 0 0 18px; color: #9da7ff; font-size: 12px; font-weight: 800; letter-spacing: 0.18em; }\n"
            "h1 { margin: 0; font-size: clamp(42px, 7vw, 78px); line-height: 0.98; letter-spacing: -0.055em; }\n"
            ".lede { max-width: 700px; margin: 30px 0 0; color: #9ca6bb; font-size: 18px; line-height: 1.7; }\n"
            ".stack { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 34px; }\n"
            ".stack span { padding: 9px 13px; border: 1px solid #252b3a; border-radius: 999px; color: #cbd2e2; font-size: 12px; }\n\n"
            ".pipeline { display: grid; gap: 12px; }\n"
            ".stage { display: grid; grid-template-columns: 54px 1fr auto; align-items: center; gap: 18px; padding: 22px; border: 1px solid #202635; border-radius: 16px; background: rgba(16, 20, 31, 0.78); }\n"
            ".stage-label { color: #7f89a2; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12px; }\n"
            ".stage h2 { margin: 0 0 5px; font-size: 17px; }\n"
            ".stage p { margin: 0; color: #8994aa; font-size: 14px; }\n"
            ".check { color: #86efac; font-size: 12px; font-weight: 700; }\n\n"
            ".next-step { display: flex; align-items: end; justify-content: space-between; gap: 30px; margin-top: 56px; padding: 30px; border-radius: 20px; background: #eef2ff; color: #0b0e16; }\n"
            ".next-step .eyebrow { color: #555fd0; }\n"
            ".next-step h2 { margin: 0; max-width: 620px; font-size: clamp(24px, 4vw, 38px); line-height: 1.08; letter-spacing: -0.035em; }\n"
            ".next-step code { padding: 12px 14px; border-radius: 10px; background: #dce1ff; color: #3d46ad; white-space: nowrap; }\n\n"
            "@media (max-width: 680px) {\n"
            "  .offline-shell { width: min(100% - 28px, 1120px); }\n"
            "  .hero { padding: 82px 0 54px; }\n"
            "  .stage { grid-template-columns: 40px 1fr; }\n"
            "  .check { grid-column: 2; }\n"
            "  .next-step { align-items: flex-start; flex-direction: column; }\n"
            "}\n"
        ),
        target("src/vite-env.d.ts"): '/// <reference types="vite/client" />\n',
    }

    return OfflineScaffold(files=files)
